### ISSUE TITLE
Unable to create dynamic Policy Template from Management UI

### ISSUE THREAD

**Issue by stojkovicv** [5G-MAG/rt-5gms-application-provider#45]
## Description

Management UI is unable to successfully conduct Create operation for Policy templates due to, most likely, not enabled `open5gs_integration` field in `yaml` configuration file for the Application Function.

Can we set this field to always be enabled for the operating Application Function?

**Comment by rjb1000** [comment]
> Can we set this field to always be enabled for the operating Application Function?

I don't think so. Enabling this feature causes the 5GMS AF to attempt to register with the NRF and to attempt to invoke the PCF. If neither of these Network Functions is present in the deployment, the 5GMS AF will probably become unhappy.

> Management UI is unable to successfully conduct Create operation for Policy templates due to, most likely, not enabled `open5gs_integration` field in YAML configuration file for the Application Function.

It should still be possible to successfully create a Policy Template without enabling the integration with the 5G Core. It may be that this failure is for another reason.

Assigning to @davidjwbbc to investigate.

**Comment by davidjwbbc** [comment]
The situation is that the AF will return a 400 response if the the PolicyTemplate doesn't parse or validate, or when the open5gs intergration is disabled. So you don't actually know if it's because the feature is disabled or if the request was bad somehow. However the error response will have the full ProblemDetail object returned.

On the python side, the M1Client will raise an `M1ClientError` exception with the 400 `status_code` and the reason set to "M1 Operation failed: " + the ProblemDetail JSON string. The M1Session object will not catch the exception and it will be passed onto the the FastAPI server.

I note that the FastAPI server (`management-ui/server.py`) does not catch the M1Error, M1ClientError or M1ServerError exceptions (i.e. no `@app.exception_handler(M1Error)` decorated function) and probably should, converting these into HTTPException exceptions for FastAPI to report back to the client. This would at least return back to the client the error message from the AF that indicates that the operation failed due to `open5gsIntegration` not being `true`.

**Comment by rjb1000** [comment]
Notwithstanding the point about handling exceptions better in the FastAPI server, @davidjwbbc, I wonder what you think about changing the behaviour of the 5GMS AF so that it allows Policy Templates to be created, even when the 5G Core integration is disabled.

In this case, the 5GMS AF could return _200 OK_ with a *ProblemDetails* JSON response body warning the invoker that the 5GMS AF is not integrated with a 5G Core and therefore instantiating the Policy Template will have no effect.

I suppose the 5GMS AF could kick the can down the road a bit: instead of rejecting the Policy Template at the provisioning interface (reference point M1) it could return an error to any Media Session Handler attempting to instantiate a Dynamic Policy based on the Policy Template as a blanket response (reference point M5) when there is no integration with a 5G Core.

**Comment by davidjwbbc** [comment]
Just adding the exception handling reveals this:
![AP-webui-PolicyTemplate-fail-20240711](https://github.com/5G-MAG/rt-5gms-application-provider/assets/9946409/5755b0cc-066a-40ba-ac50-8e8402d5b166)

I'm not in favour of allowing the AF accept the templates when it cannot use them. I think it has the correct behaviour right now which is to return a 400 error with the following problem detail:
```json
{
    "type": "/3gpp-m1/v2",
    "title": "Problem adding the policy template.",
    "status": 400,
    "detail": "Policy Templates are not available on this instance of the 5GMS Application Function.",
    "instance": "/provisioning-sessions/f722002c-3f9d-41ef-a458-93fe3c46511a/policy-templates"
}
```

Also by denying the provisioning we would never see a UE attempt a DynamicPolicy session as no dynamic policy configuration would ever be sent to the UE to indicate that it's available.

**Comment by davidjwbbc** [comment]
What could be nice is maybe changing the behaviour of the `OPTIONS` method in the AF to omit `POST` if you can't provision PolicyTemplates with the AF configuration.

**Comment by davidjwbbc** [comment]
In fact since it's quick to prototype...

![AP-webui-dynamic-policies-detection-20240711](https://github.com/5G-MAG/rt-5gms-application-provider/assets/9946409/b40434ee-36a3-45b6-af50-8ee258ea2900)

This is done by changing the `Allow` header in the response for the OPTIONS method for `.../provisioning-sessions/{provisioningSessionId}/policy-templates`  to remove `POST` if the open5gs integration is not `true`, adding a webui backend server point to check this new OPTIONS response for `POST` and then getting the webui to use a message instead of the buttons if the feature is not enabled.

**Comment by davidjwbbc** [comment]
@stojkovicv  & @rjb1000, if we're happy with this solution I'll tidy up the code and submit PRs for this repository (new policy_template_checker API on the backend server and associated client side web UI javascript changes) and the rt-5gms-application-function repository (OPTIONS change).

**Comment by rjb1000** [comment]
Sounds good to me, @davidjwbbc .

**Comment by stojkovicv** [comment]
Just to make sure @davidjwbbc - your solution doesn't radically remove Dynamic Policies creation (with values checking layer) from the UI, but instead it checks the response from OPTIONS request from AF and adapts accrodingly?
In other words, the creation will still be possible from the UI, if, hypothetically, the AF integration with open5gs is enabled?

**Comment by davidjwbbc** [comment]
> Just to make sure @davidjwbbc - your solution doesn't radically remove Dynamic Policies creation (with values checking layer) from the UI, but instead it checks the response from OPTIONS request from AF and adapts accrodingly? In other words, the creation will still be possible from the UI, if, hypothetically, the AF integration with open5gs is enabled?

Absolutely, all it does is:
```javascript
  if (policy_templates_enabled(sessionId)) {
          cell6.innerHTML = `<button onclick="setDynamicPolicy('${sessionId}')" class="btn btn-primary table-button">Set</button>
                            <button onclick="showDynamicPolicies('${sessionId}', '${sessionData.policy_template_id}')" class="btn btn-info table-button">Show</button>
                            <button onclick="deleteDynamicPolicy('${sessionId}', '${sessionData.policy_template_id}')" class="btn btn-danger table-button">Delete</button>`;
  } else {
          cell6.innerHTML = 'Dynamic Policies are not available';
  }
```

So the buttons just don't appear on the UI if the AF indicates it can't provision policy templates, but all the code is still there to do the provisioning if the AF is configured correctly.

**Comment by stojkovicv** [comment]
Alright, all approved.
